version: "3"

services:
  web:
    image: local/rmac/web
    build:
      context: ../..
      dockerfile: setup/docker/build/web/Dockerfile
      args:
        USAGE: staging
        COPY_PREFIX: setup/docker/build/web
    environment:
      LEDGER_POSTGRES_USER: ${LEDGER_POSTGRES_USER:-sql-ledger}
    ports:
      - ${LEDGER_PORT:-4293}:80
    networks:
      - private
    volumes:
      - ${LEDGERSETUP_CONFIG_PATH:-/tmp/ledgersetup/configs}:/ledgersetup/configs:ro
      - ${LEDGERSETUP_DUMPS_PATH:-/tmp/ledgersetup/dumps}:/ledgersetup/dumps:ro

  db:
    environment:
      LEDGER_POSTGRES_USER: ${LEDGER_POSTGRES_USER:-sql-ledger}
    image: local/rmac/db
    build:
      context: build/db
    networks:
      - private
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data:

networks:
  private:
